version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"

    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

    groups:
      uv-dependencies:
        patterns:
          - "*"

    labels:
      - "dependencies"
      - "dependabot"
      - "automated"
