name: Build and Deploy Python App to Self-hosted Runner

on:
  push:
    branches:
      - "main"
  # pull_request:
  #   branches:
  #     - "main"

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    environment:
      name: production

    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Tags Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{vars.DOCKERHUB_USERNAME}}/discord-bot

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{steps.meta.outputs.tags}}
        
  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: build
    environment:
      name: production
    
    steps:
    - name: Deploy Discord Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
      run: |
        echo "Starting Deployment..."
        echo "Removing existing image if present..."
        docker rmi -f ${{ needs.build.outputs.image-tag }} || echo "No existing image to remove."

        echo "Pulling image: ${{ needs.build.outputs.image-tag }}"
        docker pull ${{ needs.build.outputs.image-tag }}
        
        echo "Removing existing container if present..."
        docker rm -f discord-bot || echo "No existing container to remove."

        echo "Running the container..."
        docker run --restart always -it -v /home/discordbot-logs:/app/logs \
          -e TOKEN=${{ env.TOKEN }} \
          -e SPOTIPY_CLIENT_ID=${{ env.SPOTIPY_CLIENT_ID }} \
          -e SPOTIPY_CLIENT_SECRET=${{ env.SPOTIPY_CLIENT_SECRET }} \
          -d --name discord-bot ${{ needs.build.outputs.image-tag }}

        echo "Removing dangling images..."
        docker image prune -f

        echo "Deployment completed successfully!"
