name: Build and deploy Python app to Self-hosted runner

env:
  PYTHON_VERSION: '3.12'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}
    
    - name: Create and start virual environment
      run: |
        uv venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        uv pip install -Ur requirements.txt

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'production'

    env:
      TOKEN: ${{secrets.TOKEN}}
      SPOTIPY_CLIENT_SECRET: ${{secrets.SPOTIPY_CLIENT_SECRET}}
      SPOTIPY_CLIENT_ID: ${{secrets.SPOTIPY_CLIENT_ID}}
    
    steps:
      - name: Deploy Discord Bot to local server
        run: |
          uv run main.py
