name: Build and Deploy Python App to Self-hosted Runner

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install `uv` CLI
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create and Activate Virtual Environment
      run: |
        uv venv
        . .venv/bin/activate

    - name: Install Dependencies
      run: |
        uv pip install -Ur requirements.txt || { echo "Dependency installation failed"; exit 1; }

  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: build
    environment:
      name: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy Discord Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
      run: |
        echo "Starting Deployment..."
        tmux new-session -d -s bot_session 'uv run main.py' || { echo "Deployment failed"; exit 1; }
        echo "Deployment completed successfully!"
